Doubles the number of webservers

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -3,6 +3,9 @@
 # Ignore SC2154 for shellcheck
 # shellcheck disable=SC2154
 
+# Exit immediately if a command exits with a non-zero status
+set -e
+
 # Updates the package list
 sudo apt-get update
 
@@ -21,10 +24,15 @@ sudo sed -i '/server_name _;/a \    add_header X-Served-By '"$HOSTNAME"';' /etc/
 # Restart Nginx to apply the changes
 sudo systemctl restart nginx
 
-# Check the Nginx status
-NGINX_STATUS=$(sudo systemctl is-active nginx)
-if [ "$NGINX_STATUS" == "active" ]; then
-    echo "Nginx has been configured with a custom header 'X-Served-By: $HOSTNAME'"
+# Check the Nginx status and verify the custom header
+if sudo systemctl is-active nginx >/dev/null; then
+    if curl -sI http://localhost | grep -q "X-Served-By: $HOSTNAME"; then
+        echo "Nginx has been configured with a custom header 'X-Served-By: $HOSTNAME'"
+    else
+        echo "Failed to verify the custom header"
+        exit 1
+    fi
 else
     echo "Failed to configure Nginx"
+    exit 1
 fi
